#!/bin/bash

current_dir=$(pwd)
parent_dir=$(dirname "$current_dir")

# Copy HTML files to the parent directory if they are newer or don't exist there
for file in *.html; do
    if [ -f "$file" ]; then
        cp -n -u "$file" "$parent_dir"
    fi
done
